log4j.rootLogger=INFO,f
log4j.appender.f=org.apache.log4j.FileAppender
log4j.appender.f.File=E:\\java\\output\\log4j.htm
log4j.append.f.Append=false
log4j.appender.f.layout=org.apache.log4j.HTMLLayout
