
package com.roden.java.webservice.auto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceTest", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceTest {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://webservice/", className = "webservice.auto.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://webservice/", className = "webservice.auto.SumResponse")
    @Action(input = "http://webservice/ServiceTest/sumRequest", output = "http://webservice/ServiceTest/sumResponse")
    public int sum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservice/", className = "webservice.auto.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservice/", className = "webservice.auto.SayHelloResponse")
    @Action(input = "http://webservice/ServiceTest/sayHelloRequest", output = "http://webservice/ServiceTest/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
