
package com.roden.java.webservice.auto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceTestService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:8000/javaee/ServiceTest?wsdl")
public class ServiceTestService
    extends Service
{

    private final static URL SERVICETESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICETESTSERVICE_EXCEPTION;
    private final static QName SERVICETESTSERVICE_QNAME = new QName("http://webservice/", "ServiceTestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/javaee/ServiceTest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICETESTSERVICE_WSDL_LOCATION = url;
        SERVICETESTSERVICE_EXCEPTION = e;
    }

    public ServiceTestService() {
        super(__getWsdlLocation(), SERVICETESTSERVICE_QNAME);
    }

    public ServiceTestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICETESTSERVICE_QNAME, features);
    }

    public ServiceTestService(URL wsdlLocation) {
        super(wsdlLocation, SERVICETESTSERVICE_QNAME);
    }

    public ServiceTestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICETESTSERVICE_QNAME, features);
    }

    public ServiceTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceTestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceTest
     */
    @WebEndpoint(name = "ServiceTestPort")
    public ServiceTest getServiceTestPort() {
        return super.getPort(new QName("http://webservice/", "ServiceTestPort"), ServiceTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceTest
     */
    @WebEndpoint(name = "ServiceTestPort")
    public ServiceTest getServiceTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "ServiceTestPort"), ServiceTest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICETESTSERVICE_EXCEPTION!= null) {
            throw SERVICETESTSERVICE_EXCEPTION;
        }
        return SERVICETESTSERVICE_WSDL_LOCATION;
    }

}
